config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', :to => 'static_pages#about'
  get '/login', :to => 'sessions#new'
  post '/login', :to => 'sessions#create'
  delete '/logout', :to => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :users, :only => [:new, :create, :show]
  resources :rsvps, :only => [:create, :update, :destroy]
  resources :invites, :only => [:create, :destroy]
  resources :events
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
    belongs_to :creator,  class_name: 'User'
    has_many :rsvps, foreign_key: 'attended_event_id'
    has_many :attendees, :through => :rsvps,
                         :source => :attendee

    has_many :invites, foreign_key: 'event_id'
    has_many :invited_users, :through => :invites,
    :source => :receiver

    default_scope -> { order(created_at: :desc) }
    scope :past, -> { where("event_date < ?", Time.now) }
    scope :future, -> { where("event_date > ?", Time.now) }

    mount_uploader :thumbnail, ThumbnailUploader
    
    validates :title, presence: true
    validates :event_date, presence: true
    validates :location, presence: true
    validates :creator_id, presence: true

    def formatted_date
        self.event_date.strftime("%A, %b %d, %H:%M %p")
    end

    def going?(user)
        attendees.find_by(id: user.id)
    end
end

app/models/invite.rb
class Invite < ApplicationRecord
  belongs_to :sender, class_name: 'User'
  belongs_to :receiver, class_name: 'User'
  belongs_to :event
end

app/models/rsvp.rb
class Rsvp < ApplicationRecord
    belongs_to :attendee, class_name: 'User'
    belongs_to :attended_event, class_name: 'Event'
    validates :attended_event_id, uniqueness: { scope: :attendee_id }

end

app/models/user.rb
class User < ApplicationRecord
    before_save :downcase_email

    has_many :events, foreign_key: 'creator_id', class_name: 'Event'
    has_many :rsvps, foreign_key: 'attendee_id'
    
    has_many :attended_events, :through => :rsvps,
                               :source => :attended_event

                               

    has_many :sent_invites, foreign_key: 'sender_id', 
                           class_name: 'Invite'

    has_many :received_invites, foreign_key: 'receiver_id', 
                           class_name: 'Invite'

    validates :name, presence: true
    validates :email, presence: true, uniqueness: true

    def invite(user, event)
        sent_invites << Invite.new( receiver: user, event: event )
    end

    def has_invite_to?(event)
        ! received_invites.find_by(event: event).nil?
    end

    def reject(invite)
        received_invites.delete(invite)
    end


    def attending?(event)
        attended_events.include?(event)
    end

    def attend(event)
        attended_events << event
    end

    def miss(event)
        attended_events.delete(event)
    end


    private
    def downcase_email
        email.downcase!
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    include RsvpsHelper

    def require_login
        unless logged_in?
            flash[:info] = "You must log in first."
            store_location
            redirect_to login_path
        end
    end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
    before_action :require_login

    def new
        @event = current_user.events.build
    end

    def show
        @event = Event.find(params[:id])
        
        ban_list = @event.attendees + @event.invited_users + [current_user]
        @users = User.where.not(id: ban_list)
    end

    def create
        @event = current_user.events.build(event_params)
        if @event.save
            flash[:success] = "Event posted."
            redirect_to @event
        else
            render 'new'
        end
    end

    private
    def event_params
        params.require(:event).permit(:thumbnail, :title, :event_date,
                                      :location, :description)
    end

end

app/controllers/invites_controller.rb
class InvitesController < ApplicationController
    def create
        @receiver = User.find(params[:receiver_id])
        @event = Event.find(params[:event_id])

        @invite = current_user.invite(@receiver, @event)
        respond_to do |format|
            format.html { redirect_to @event }
            format.js
        end
    end

    def destroy
        @invite = Invite.find(params[:id])
        current_user.reject(@invite)
        respond_to do |format|
            format.html { redirect_to @event }
            format.js
        end
    end

    private
    def invite_params
        params.require(:invite).permit(:receiver_id, :event_id)
    end
end

app/controllers/rsvps_controller.rb
class RsvpsController < ApplicationController
    before_action :require_login

    def create
        @event = Event.find(params[:attended_event_id])
        current_user.attend(@event)
        redirect_to @event
    end

    def update
    end

    def destroy
        @rsvp = current_user.rsvps.find_by(id: params[:id]).delete
        redirect_back fallback_location: root_url
    end

    private
    def rsvp_params
        params.require(:rsvp).permit(:attended_event)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email] )
    if @user
      log_in @user
      redirect_back_or(@user)
    else
      flash.now[:danger] = "No user by that name..."
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    flash[:success] = "Logged out"
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    @past = Event.past
    @future = Event.future
  end

  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @attended_events = @user.attended_events
  end
  
  private
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include SessionsHelper
    
    def base_title(title)
        base = "Private Events"
        title.empty? ? base : title + ' | ' + base
    end
end

app/helpers/event_invites_helper.rb
module EventInvitesHelper
end

app/helpers/events_helper.rb
module EventsHelper
    def event_image(event)
        if event.thumbnail?
            image_tag event.thumbnail.url, class: 'card-img-top'
        else
            image_tag 'https://via.placeholder.com/100x50', class: 'card-img-top'
        end
    end

end

app/helpers/rsvps_helper.rb
module RsvpsHelper
    def maybe_delete_invite(invite)
        invite.destroy if invite
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id unless logged_in? 
    end

    def current_user
        @current_user ||= User.find(session[:user_id])
    end

    def log_out
        @current_user = nil
        session[:user_id] = nil
    end

    def logged_in?
        !session[:user_id].nil?
    end

    def store_location
        session[:original_url] = request.original_url if request.get?
    end

    def redirect_back_or(default)
        redirect_to (session[:original_url] || default)
        session.delete(:original_url)
    end
        
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_event.html.erb
<div id="event-<%= event.id %>" class="event border m-1">
    <div class="card-body">
        <%= link_to event_image(event), event %>
        
        <div class="d-flex pt-2">
            <div class="flashy-date mr-4 text-center left">
                <span class="month"><%= event.event_date.strftime("%b") %></span>
                <span class="day"><%= event.event_date.day %></span>
            </div>
            <div class="right">
                <h5 class="card-title m-0"><%= link_to event.title, event, class: 'link-normal' %></h5>
                <div class="details">
                    <%= event.formatted_date %>
                    <p class="card-text"><%= event.location %></p>
                </div>
                <span class="attending text-muted">
                    <%= fa_icon('user', text: event.attendees.count ) %>
                </span>
            </div>
        </div>
    </div>
</div>

app/views/events/new.html.erb
<% provide(:title, 'Create event' ) %>

<h1>Create Event</h1>
<%= form_for @event do |f| %>
    <%= render 'shared/errors', object: f.object %>

    <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label :description %>
        <%= f.text_area :description, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label 'where' %>
        <%= f.text_field :location, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label 'when' %>
        <%= f.datetime_select :event_date, class: 'form-control' %>
    </div>

    <div class="form-group">
        <%= f.label "Image" %>
        <%= f.file_field :thumbnail %>
    </div>

    <%= f.submit "Post event", class: 'btn btn-success' %>
<% end %>

app/views/events/show.html.erb
<% provide(:title, @event.title) %>

<div class="mb-4">
    <h1 class="display-4"><%= @event.title %></h1>
    <%= event_image(@event) %>
</div>
<div id="event-<%= @event.id %>" class="event show row">
    <div class="col-6">
        <h2>Description</h2>
        <%= @event.description %>        
    </div>
    <div class="col-6">
        <h2>Info</h2>
        <table class="table info">
            <tr>
                <th>When</th>
                <td><%= @event.formatted_date %></td>
            </tr>
            <tr>
                <th>Where</th>
                <td><%= @event.location %></td>
            </tr>
            <tr>
                <th>Contact</th>
                <td><%= link_to @event.creator.email, @event %></td>
            </tr>
        </table>
    </div>
    <hr class="mb-4" />
    <div class="col-6">
        <%= render 'shared/attendance' %>
    </div>
    <div class="col-6">
        <h4>Invite people</h4>
        <div class="invite_for">
            <% @users.each do |user| %>
                <%= render 'shared/invite_form', object: user %>
            <% end %>
        </div>
    </div>
</div>

app/views/invites/_cancel.html.erb
<%= form_for(object.received_invites.find_by(receiver_id: object.id),
             html: { method: :delete }) do |f| %>
    <div class="d-flex justify-content-between">
        <span><%= object.name %></span>
        <%= f.submit "Cancel", class: 'btn btn-danger' %>
    </div>
<% end %>

app/views/invites/_invite.html.erb
<div class="invite-<%= invite.id %>">
    <p><%= invite.sender.name %> invited you to <%= invite.event.title %></p>
    <div class="d-flex">
        <%= link_to 'Accept', rsvps_url(@rsvp, :event_id => invite.event.id), method: :post %>
        <%= link_to 'Reject', invites_url(invite), method: :delete %>
    </div>
</div>

app/views/invites/_send.html.erb
<%= form_for(current_user.sent_invites.build, remote: true ) do |f| %>
    <div class="d-flex justify-content-between mt-2">
        <%= object.name %>
        <%= f.submit "Invite", class: 'btn btn-outline-success' %>
    </div>

    <%= hidden_field_tag :event_id, @event.id %>
    <%= hidden_field_tag :receiver_id, object.id %>
<% end %>

app/views/invites/create.js.erb
$("#invite_form").html("<%= escape_javascript(render('invites/send')) %>");

app/views/layouts/_account_links.html.erb
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="event_invites" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Invites
        <span class="badge badge-pill badge-dark text-light"><%= current_user.received_invites.count %></span>
    </a>
    <div class="dropdown-menu" aria-labelledby="event_invites">
        <%= render current_user.received_invites %>
    </div>
</li>
<li class="nav-item dropdown">
    <a class="nav-link dropdown-toggle" href="#" id="account_links" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        Account
    </a>
    <div class="dropdown-menu" aria-labelledby="account_links">
        <%= link_to 'Create Event', new_event_path, class: 'dropdown-item' %>
        <%= link_to 'Profile', user_path(current_user), class: 'dropdown-item' %>
        <%= link_to 'Logout', logout_path, class: 'dropdown-item' %>
    </div>
</li>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
     <div class="alert alert-<%= message_type %>"><%= message %></div>
 <% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-danger mb-2">
    <div class="container">
        <%= link_to 'Private Events', root_url, class: 'navbar-brand' %>
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <%= link_to 'About', about_path, class: 'nav-link' %>
            </li>
        </ul>
        <ul class="navbar-nav ml-auto">
            <% if logged_in? %>
                <%= render 'layouts/account_links' %>
            <% else %>
            <li class="nav-item active">
                <%= link_to 'Login', login_path, class: 'nav-link' %>
            </li>
            <% end %>
        </ul>
    </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= base_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <%= render 'layouts/flash' %>
    <div class="container">
      <%= yield %>
      <pre>
        <%= params.inspect %>
    </pre>
    </div>
    
  </body>
</html>

app/views/rsvps/_attend.html.erb
<%= form_for(current_user.rsvps.build) do |f| %>
    <div><%= hidden_field_tag :attended_event_id, @event.id %></div>
    <%= f.submit "Attend", class: 'btn btn-success' %>
<% end %>

app/views/rsvps/_miss.html.erb
<%= form_for(current_user.rsvps.find_by(attendee_id: current_user.id),
            html: { method: :delete }) do |f| %>
    <%= f.submit "Miss", class: 'btn btn-danger' %>
<% end %>

app/views/shared/_attendance.html.erb
<div class="attend-event">
    <h4>Guest list</h4>
    <% if @event.attendees.any? %>
        <ul class="event-attendees list-group list-group-flush mb-2">
            <%= render @event.attendees %>
        </ul>
    <% end %>

     <div id="attending-form pt-5 mt-2">
        <%= render 'shared/attending_form' %>
    </div>
</div>

app/views/shared/_attending_form.html.erb
<% unless @event.going?(current_user) %>
    <%= render 'rsvps/attend' %>
 <% else %>
    <%= render 'rsvps/miss' %>
<% end %>

app/views/shared/_errors.html.erb
<% if object.errors.any? %>
    <ul id="errors" class="bg-danger text-white">
        <% object.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
<% end %>

app/views/shared/_invite_form.erb
<% unless object.has_invite_to?(@event) %>
    <%= render 'invites/send', object: object %>
<% else %>
    <%= render 'invites/cancel', object: object %>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>

<h1>What is "Private Events"</h1>
<h2>A simple app which allows users to create events and allows other users to signup for created events.</h2>

<%= link_to 'https://www.theodinproject.com/courses/ruby-on-rails/lessons/associations#null' %>

<h3>Here's how we are going to do it:</h3>
<h4>users & sign up</h4>
<ul>
    <li>rails g model User name:string email:string</li>
    <li>users controller new/show/destroy</li>
    <li>allow users to sign in</li>
    <li>store the session</li>
</ul>

<h4>events</h4>
<ul>
    <li>rails g model Event title:string description:string user:reference datetime:datetime location:string</li>
    <li>show event</li>
    <li>allow users to signup for event</li>
    <li>show event on user/show</li>
    <li>show all events on homepage</li>
    <li>create events form</li>
    <li>allow owners to edit/delete events</li>
</ul>

app/views/static_pages/home.html.erb
<ul class="nav nav-pills" id="eventsTab" role="tablist">
  <li class="nav-item">
    <a class="nav-link" id="past-tab" data-toggle="pill" href="#past" role="tab" aria-controls="past" aria-selected="false">Past</a>
  </li>
  <li class="nav-item">
    <a class="nav-link active" id="future-tab" data-toggle="pill" href="#future" role="tab" aria-controls="future" aria-selected="true">Upcoming</a>
  </li>
</ul>

<!-- Tab panes -->
<div class="tab-content">
  <div class="tab-pane" id="past" role="tabpanel" aria-labelledby="past-tab">
    <div class="row">
        <%= render @past %>
    </div>
  </div>
  <div class="tab-pane active" id="future" role="tabpanel" aria-labelledby="future-tab">
    <div class="row">
        <%= render @future %>
    </div>
  </div>
</div>

app/views/users/_user.html.erb
<li class="list-group-item user-<%= user.id %>">
    <%= user.name %>
</li>

app/views/users/new.html.erb
<h1>Register</h1>
<p>Already a user? <%= link_to 'Sign in here.', login_path %>

<%= form_for @user do |f| %>
    <%= render 'shared/errors', object: f.object %>
    <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name %>
    </div>

    <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field :email %>
    </div>

    <div class="form-group">
        <%= f.submit 'Register', class: 'btn btn-success' %>
    </div>
<% end %>

app/views/users/show.html.erb
<% provide(:title, "User #{@user.name} ") %>

<h1><%= @user.name %> </h1>
<div class="row">
    <div class="col-6">
        <h2>Created events</h2>
        <%= render @user.events %>
    </div>
    <div class="col-6">
        <h2>Attending events</h2>
        <%= render @attended_events %>
    </div>
</div>